import { matches } from "./glob.js"; import type { Finding,ParsedPatch,ReviewOptions } from "./types.js";
const testPath=/(^|\/)(__tests__|test|tests|spec)(\/|\.)|\.(test|spec)\.[cm]?[jt]sx?$/i;
const codePath=/\.(ts|tsx|js|jsx|mjs|cjs|py|go|rs|java|cs|php|rb|swift|kt)$/i;
const schemaPath=/(schema|model|entity|database)|\.(sql|prisma)$/i;
const migrationPath=/(^|\/)(migrations?|alembic|db\/migrate)(\/|$)/i;
const dependencyPath=/(^|\/)(package(-lock)?\.json|pnpm-lock\.yaml|yarn\.lock|requirements.*\.txt|pyproject\.toml|poetry\.lock|go\.mod|cargo\.toml)$/i;
const generatedPath=/(^|\/)(generated|gen|vendor|dist|build|coverage)(\/|$)|\.generated\./i;
const secretPatterns=[/sk-[A-Za-z0-9_-]{20,}/,/AKIA[0-9A-Z]{16}/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/(?:password|secret|token|api[_-]?key)\s*[:=]\s*["'][^"']{8,}["']/i];
function secretFinding(path:string,lines:string[]):Finding|undefined{if(!lines.some(line=>secretPatterns.some(p=>p.test(line))))return;return{code:"PL201_SECRET_ADDITION",severity:"high",title:"Potential secret added",path,evidence:"An added line matched a credential or private-key detector; the matched value is redacted."};}
export function runRules(patch:ParsedPatch,options:ReviewOptions={}):Finding[]{const out:Finding[]=[];const changed=patch.files.map(f=>f.path);const hasTest=changed.some(p=>testPath.test(p));const hasMigration=changed.some(p=>migrationPath.test(p));
 for(const file of patch.files){const secret=secretFinding(file.path,file.addedLines);if(secret)out.push(secret);if(options.allowedPaths?.length&&!matches(file.path,options.allowedPaths))out.push({code:"PL203_SCOPE_ESCAPE",severity:"high",title:"File changed outside declared scope",path:file.path,evidence:`Allowed paths: ${options.allowedPaths.join(", ")}`});if(dependencyPath.test(file.path))out.push({code:"PL205_DEPENDENCY_CHANGE",severity:"medium",title:"Dependency surface changed",path:file.path,evidence:"A dependency manifest or lockfile changed."});if(generatedPath.test(file.path))out.push({code:"PL206_GENERATED_EDIT",severity:"medium",title:"Generated or derived file changed",path:file.path,evidence:"The path matches a generated/build/vendor convention."});}
 if(changed.some(p=>codePath.test(p)&&!testPath.test(p))&&!hasTest)out.push({code:"PL202_CODE_WITHOUT_TEST",severity:"medium",title:"Code changed without a test change",evidence:"At least one source file changed and no test/spec path changed."});
 if(changed.some(p=>schemaPath.test(p))&&!hasMigration)out.push({code:"PL204_SCHEMA_WITHOUT_MIGRATION",severity:"high",title:"Schema changed without migration",evidence:"A schema/model/database file changed but no migration path changed."});
 const maxFiles=options.maxChangedFiles??40,maxLines=options.maxChangedLines??1200;if(patch.files.length>maxFiles||patch.additions+patch.deletions>maxLines)out.push({code:"PL207_OVERSIZED_PATCH",severity:"medium",title:"Patch exceeds review budget",evidence:`${patch.files.length} files and ${patch.additions+patch.deletions} changed lines exceed ${maxFiles} files or ${maxLines} lines.`});
 return out.sort((a,b)=>({high:0,medium:1,low:2}[a.severity]-{high:0,medium:1,low:2}[b.severity])||a.code.localeCompare(b.code)||(a.path??"").localeCompare(b.path??""));}
